name: PostTweet

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 0,6'
  - cron: '0 1 * * 0,6'
  - cron: '0 2 * * 0,6'
  - cron: '0 3 * * 0,6'
  - cron: '0 4 * * 0,6'
  - cron: '0 5 * * 0,6'
  - cron: '0 6 * * 0,6'
  - cron: '0 7 * * 0,6'
  - cron: '0 8 * * *'
  - cron: '0 9 * * *'
  - cron: '0 10 * * *'
  - cron: '0 11 * * *'
  - cron: '0 12 * * *'
  - cron: '0 13 * * *'
  - cron: '0 14 * * *'
  - cron: '0 15 * * *'
  - cron: '0 21 * * *'
  - cron: '0 22 * * *'
  - cron: '0 23 * * 0,6'

jobs:
  PostTweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.10'
          architecture: 'x64'
      - name: Install packages
        run: sudo apt-get install -y mecab libmecab-dev mecab-ipadic-utf8
      - name: Get MeCab dictionary
        run: git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git
      - name: Setup MeCab dictionary
        run: ./bin/install-mecab-ipadic-neologd -n -y
        working-directory: ./mecab-ipadic-neologd
      - name: Setup MeCab configure
        run: echo dicdir = `mecab-config --dicdir`"/mecab-ipadic-neologd" > mecabrc && sudo cp mecabrc /usr/local/etc/
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements_pt.txt
      - name: Run Python
        run: python PostTweet.py migrate
        env:
            API_KEY: ${{secrets.API_KEY}}
            API_KEY_SECRET: ${{secrets.API_KEY_SECRET}}
            ACCESS_TOKEN_S: ${{secrets.ACCESS_TOKEN_S}}
            ACCESS_TOKEN_SECRET_S: ${{secrets.ACCESS_TOKEN_SECRET_S}}
            ACCESS_TOKEN_P: ${{secrets.ACCESS_TOKEN_P}}
            ACCESS_TOKEN_SECRET_P: ${{secrets.ACCESS_TOKEN_SECRET_P}}
