name: Reply

on:
  workflow_dispatch:
  #schedule:
  #- cron: '0 3 * * *'
  #- cron: '0 7 * * *'
  #- cron: '0 11 * * *'
  #- cron: '0 15 * * *'
  #- cron: '0 19 * * *'
  #- cron: '0 23 * * *'

jobs:
  Reply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.10'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install packages
        run: sudo apt-get install -y mecab libmecab-dev mecab-ipadic-utf8
      - name: Get MeCab dictionary
        run: git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git
      - name: Setup MeCab dictionary
        run: ./bin/install-mecab-ipadic-neologd -n -y
        working-directory: ./mecab-ipadic-neologd
      - name: Setup MeCab configure
        run: echo dicdir = `mecab-config --dicdir`"/mecab-ipadic-neologd" > mecabrc && sudo cp mecabrc /usr/local/etc/
      - name: Install dependencies
        run: pip install -r requirements_r.txt
      - name: Run Python
        run: python Reply.py migrate
        env:
            API_KEY: ${{secrets.API_KEY}}
            API_KEY_SECRET: ${{secrets.API_KEY_SECRET}}
            ACCESS_TOKEN_S: ${{secrets.ACCESS_TOKEN_S}}
            ACCESS_TOKEN_SECRET_S: ${{secrets.ACCESS_TOKEN_SECRET_S}}
            ACCESS_TOKEN_P: ${{secrets.ACCESS_TOKEN_P}}
            ACCESS_TOKEN_SECRET_P: ${{secrets.ACCESS_TOKEN_SECRET_P}}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "ステータス更新" -a
